---
displaymanagers:
  - sddm

basicSetup: false
sysconfigSetup: false

defaultDesktopEnvironment:
  executable: "/usr/bin/startplasma-x11"
  desktopFile: "plasma"

sddm:
  configuration_file: "/etc/sddm.conf"
