---
dontChroot: false
timeout: 120

script:
  - "rm -f /etc/mkinitcpio.d/linux.preset"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "plymouth-set-default-theme fangos"
  - "printf '%s\n' 'ALL_kver=\"/boot/vmlinuz-linux\"' 'PRESETS=(\"default\" \"fallback\")' 'default_image=\"/boot/initramfs-linux.img\"' 'fallback_image=\"/boot/initramfs-linux-fallback.img\"' 'fallback_options=\"-S autodetect\"' > /etc/mkinitcpio.d/linux.preset"
